### ISSUE TITLE
Toasted Afk console error

### ISSUE THREAD

**Issue by hero23550** [SerbanHiro/ToastedAFK#1]
Server version:- 1.19.4
Software:- Paper
Plugins:- Viaversion , viabackwards 
Error on console:-

```
[12:10:50] [Server thread/ERROR]: Could not pass event OnRegionLeftEvent to ToastedAFK v2.0
--
1130 | java.lang.NullPointerException: Cannot invoke "me.serbob.toastedafk.Classes.PlayerStats.getLevelTimer()" because the return value of "java.util.Map.get(Object)" is null
1131 | at me.serbob.toastedafk.Templates.CoreHelpers.removePlayer(CoreHelpers.java:103) ~[ToastedAFK-2.0.jar:?]
1132 | at me.serbob.toastedafk.Events.Custom.PlayerRegionHandler.onRegionLeft(PlayerRegionHandler.java:20) ~[ToastedAFK-2.0.jar:?]
1133 | at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor890.execute(Unknown Source) ~[?:?]
1134 | at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
1135 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-550]
1136 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
1137 | at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-550]
1138 | at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-550]
1139 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
1140 | at me.serbob.toastedafk.Events.Custom.Listener.RegionRelatedEventsHandler.onPlayerQuit(RegionRelatedEventsHandler.java:41) ~[ToastedAFK-2.0.jar:?]
1141 | at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor884.execute(Unknown Source) ~[?:?]
1142 | at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
1143 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-550]
1144 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
1145 | at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-550]
1146 | at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-550]
1147 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
1148 | at net.minecraft.server.players.PlayerList.remove(PlayerList.java:592) ~[paper-1.19.4.jar:git-Paper-550]
1149 | at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2121) ~[?:?]
1150 | at net.minecraft.server.network.ServerGamePacketListenerImpl.disconnect(ServerGamePacketListenerImpl.java:533) ~[?:?]
1151 | at net.minecraft.server.network.ServerGamePacketListenerImpl.disconnect(ServerGamePacketListenerImpl.java:474) ~[?:?]
1152 | at org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer.kickPlayer(CraftPlayer.java:612) ~[paper-1.19.4.jar:git-Paper-550]
1153 | at com.nickuc.login.ωωξΠζΨΛζροθδβγ.a(:81) ~[?:?]
1154 | at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-550]
1155 | at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-550]
1156 | at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-550]
1157 | at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-550]
1158 | at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-550]
1159 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-550]
1160 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
1161 | at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by SerbanHiro** [comment]
Can you tell me how you were able to achieve that error? I've tried replicating it but I don't get that

**Comment by hero23550** [comment]
Players in my server tried to go in and out of afk region again and again and sometimes stood between non afk and afk region

**Comment by SerbanHiro** [comment]
U using latest version? (2.0.1.3)

**Comment by SerbanHiro** [comment]
Should be fixed on latest version.
