### ISSUE TITLE
Does not seem to work with 1.20.6

### ISSUE THREAD

**Issue by IasonKalaitzakis** [SerbanHiro/ToastedAFK#3]
`Could not pass event OnRegionEnteredEvent to ToastedAFK v2.0.1.3
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at ToastedAFK-2.0.1.3.jar/me.serbob.toastedafk.Managers.VersionManager.isVersion1_12OrBelow(VersionManager.java:10) ~[ToastedAFK-2.0.1.3.jar:?]
        at ToastedAFK-2.0.1.3.jar/me.serbob.toastedafk.Commands.ALLVersionsCommandExecuter.sendCUSTOMAllVersionsTitleScreen(ALLVersionsCommandExecuter.java:31) ~[ToastedAFK-2.0.1.3.jar:?]
        at ToastedAFK-2.0.1.3.jar/me.serbob.toastedafk.Templates.CoreHelpers.addPlayer(CoreHelpers.java:95) ~[ToastedAFK-2.0.1.3.jar:?]
        at ToastedAFK-2.0.1.3.jar/me.serbob.toastedafk.Events.Custom.PlayerRegionHandler.onRegionEnter(PlayerRegionHandler.java:17) ~[ToastedAFK-2.0.1.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor759.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-115-9d6f2cc]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at ToastedAFK-2.0.1.3.jar/me.serbob.toastedafk.Events.Custom.Listener.RegionRelatedEventsHandler.lambda$updateRegions$1(RegionRelatedEventsHandler.java:107) ~[ToastedAFK-2.0.1.3.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-115-9d6f2cc]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`
        
Plugin does not seem to work correctly with 1.20.6, any plans to update it? Thanks in advance, love the plugin :)

**Comment by SerbanHiro** [comment]
Will be fixed
